name: great-expectations
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas==1.5.*
    - numpy==1.23.*
    - seaborn==0.12.*
    - jupyterlab==3.4.*
    - great_expectations==0.15.*
    - -e .